2012/12/15 17:07:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 17:08:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 17:08:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 17:09:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 17:09:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 17:10:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 17:10:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 17:11:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 17:13:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 18:01:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 18:01:47 [error] [php] copy(/mnt/host/travelagency/assets/aa604d8b/js/ckeditor/lang/bn.js) [<a href='function.copy'>function.copy</a>]: failed to open stream: Input/output error (/mnt/host/yii/framework/utils/CFileHelper.php:130)
Stack trace:
#0 /mnt/host/yii/framework/utils/CFileHelper.php(135): copyDirectoryRecursive()
#1 /mnt/host/yii/framework/utils/CFileHelper.php(135): copyDirectoryRecursive()
#2 /mnt/host/yii/framework/utils/CFileHelper.php(59): copyDirectoryRecursive()
#3 /mnt/host/yii/framework/web/CAssetManager.php(249): copyDirectory()
#4 /mnt/host/travelagency/protected/extensions/bootstrap/components/Bootstrap.php(458): CAssetManager->publish()
#5 /mnt/host/travelagency/protected/extensions/bootstrap/components/Bootstrap.php(163): Bootstrap->getAssetsUrl()
#6 /mnt/host/travelagency/protected/extensions/bootstrap/components/Bootstrap.php(124): Bootstrap->registerAssetCss()
#7 /mnt/host/travelagency/protected/extensions/bootstrap/components/Bootstrap.php(102): Bootstrap->registerCoreCss()
#8 /mnt/host/yii/framework/base/CModule.php(388): Bootstrap->init()
#9 /mnt/host/yii/framework/base/CModule.php(493): CWebApplication->getComponent()
#10 /mnt/host/yii/framework/base/CApplication.php(146): CWebApplication->preloadComponents()
#11 /mnt/host/yii/framework/YiiBase.php(127): CWebApplication->__construct()
#12 /mnt/host/yii/framework/YiiBase.php(100): createApplication()
#13 /mnt/host/travelagency/index.php(13): createWebApplication()
REQUEST_URI=/index.php/site/login
in /mnt/host/travelagency/protected/extensions/bootstrap/components/Bootstrap.php (458)
in /mnt/host/travelagency/protected/extensions/bootstrap/components/Bootstrap.php (163)
in /mnt/host/travelagency/protected/extensions/bootstrap/components/Bootstrap.php (124)
2012/12/15 18:02:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 18:02:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 18:07:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/15 18:55:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in /mnt/host/yii/framework/web/CWebApplication.php:287
Stack trace:
#0 /mnt/host/yii/framework/web/CWebApplication.php(142): CWebApplication->runController('favicon.ico')
#1 /mnt/host/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /mnt/host/travelagency/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
---
2012/12/17 21:14:45 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1130] Host '192.168.2.11' is not allowed to connect to this MySQL server' in G:\GitHub\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 G:\GitHub\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 G:\GitHub\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 G:\GitHub\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 G:\GitHub\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 G:\GitHub\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 G:\GitHub\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 G:\GitHub\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 G:\GitHub\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 G:\GitHub\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 G:\GitHub\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 G:\GitHub\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 G:\GitHub\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 G:\GitHub\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 G:\GitHub\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 G:\GitHub\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 g:\GitHub\travelagency\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model
HTTP_REFERER=http://kamran.dev.travelagency.com:81/index.php/gii/default/index
---
2012/12/17 21:16:57 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'user1'@'192.168.2.11' (using password: YES)' in G:\GitHub\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 G:\GitHub\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 G:\GitHub\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 G:\GitHub\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 G:\GitHub\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 G:\GitHub\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 G:\GitHub\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 G:\GitHub\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 G:\GitHub\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 G:\GitHub\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 G:\GitHub\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 G:\GitHub\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 G:\GitHub\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 G:\GitHub\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 G:\GitHub\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 G:\GitHub\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 g:\GitHub\travelagency\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model
---
2012/12/17 21:17:21 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1044] Access denied for user 'user1'@'192.168.2.11' to database 'travelagency'' in G:\GitHub\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 G:\GitHub\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 G:\GitHub\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 G:\GitHub\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 G:\GitHub\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 G:\GitHub\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 G:\GitHub\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 G:\GitHub\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 G:\GitHub\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 G:\GitHub\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 G:\GitHub\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 G:\GitHub\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 G:\GitHub\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 G:\GitHub\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 G:\GitHub\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 G:\GitHub\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 g:\GitHub\travelagency\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model
---
2012/12/17 21:19:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'user1@192.168.2.11'@'192.168.2.11' (using password: YES)' in G:\GitHub\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 G:\GitHub\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 G:\GitHub\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 G:\GitHub\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 G:\GitHub\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 G:\GitHub\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 G:\GitHub\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 G:\GitHub\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 G:\GitHub\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 G:\GitHub\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 G:\GitHub\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 G:\GitHub\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 G:\GitHub\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 G:\GitHub\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 G:\GitHub\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 G:\GitHub\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 g:\GitHub\travelagency\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model
---
2012/12/17 21:19:23 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'user1@192.168.2.11'@'192.168.2.11' (using password: YES)' in G:\GitHub\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 G:\GitHub\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 G:\GitHub\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 G:\GitHub\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 G:\GitHub\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 G:\GitHub\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 G:\GitHub\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 G:\GitHub\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 G:\GitHub\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 G:\GitHub\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 G:\GitHub\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 G:\GitHub\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 G:\GitHub\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 G:\GitHub\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 G:\GitHub\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 G:\GitHub\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 g:\GitHub\travelagency\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model
---
2012/12/17 21:19:44 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1130] Host '192.168.2.11' is not allowed to connect to this MySQL server' in G:\GitHub\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 G:\GitHub\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 G:\GitHub\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 G:\GitHub\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 G:\GitHub\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 G:\GitHub\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 G:\GitHub\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 G:\GitHub\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 G:\GitHub\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 G:\GitHub\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 G:\GitHub\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 G:\GitHub\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 G:\GitHub\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 G:\GitHub\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 G:\GitHub\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 G:\GitHub\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 g:\GitHub\travelagency\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model
---
2012/12/17 21:21:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'user1@192.168.2.11'@'192.168.2.11' (using password: YES)' in G:\GitHub\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 G:\GitHub\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 G:\GitHub\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 G:\GitHub\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 G:\GitHub\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 G:\GitHub\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 G:\GitHub\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 G:\GitHub\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 G:\GitHub\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 G:\GitHub\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 G:\GitHub\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 G:\GitHub\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 G:\GitHub\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 G:\GitHub\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 G:\GitHub\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 G:\GitHub\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 g:\GitHub\travelagency\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model
---
2012/12/17 21:22:41 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[42000] [1044] Access denied for user 'user1'@'' to database 'travelagency'' in G:\GitHub\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 G:\GitHub\yii\framework\db\CDbConnection.php(331): CDbConnection->open()
#1 G:\GitHub\yii\framework\db\CDbConnection.php(309): CDbConnection->setActive(true)
#2 G:\GitHub\yii\framework\base\CModule.php(388): CDbConnection->init()
#3 G:\GitHub\yii\framework\base\CModule.php(104): CModule->getComponent('db')
#4 G:\GitHub\yii\framework\gii\generators\model\ModelCode.php(57): CModule->__get('db')
#5 G:\GitHub\yii\framework\web\CFormModel.php(40): ModelCode->init()
#6 G:\GitHub\yii\framework\gii\CCodeGenerator.php(154): CFormModel->__construct()
#7 G:\GitHub\yii\framework\gii\CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 G:\GitHub\yii\framework\web\actions\CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 G:\GitHub\yii\framework\web\CController.php(309): CInlineAction->runWithParams(Array)
#10 G:\GitHub\yii\framework\web\CController.php(287): CController->runAction(Object(CInlineAction))
#11 G:\GitHub\yii\framework\web\CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 G:\GitHub\yii\framework\web\CWebApplication.php(283): CController->run('')
#13 G:\GitHub\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('gii/model')
#14 G:\GitHub\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#15 g:\GitHub\travelagency\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/index.php/gii/model
---
2012/12/17 21:29:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "admin".' in G:\GitHub\yii\framework\web\CWebApplication.php:287
Stack trace:
#0 G:\GitHub\yii\framework\web\CWebApplication.php(142): CWebApplication->runController('admin')
#1 G:\GitHub\yii\framework\base\CApplication.php(162): CWebApplication->processRequest()
#2 g:\GitHub\travelagency\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php/admin
---
2012/12/17 21:41:03 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'travelagency.flight_passenger' doesn't exist. The SQL statement executed was: SHOW COLUMNS FROM `flight_passenger`.
in g:\GitHub\travelagency\index.php (13)
